# [Nibabel images](https://nipy.org/nibabel/nibabel_images.html)

In [3]:
import os
import numpy as np
import nibabel as nib
from nibabel.testing import data_path

In [4]:
example_file = os.path.join(data_path, 'example4d.nii.gz')

In [5]:
img = nib.load(example_file)

In [6]:
img

In [7]:
# img. #[tab completion]

In [8]:
img.dataobj

In [12]:
# Set numpy to print only 2 decimal digits for neatness
np.set_printoptions(precision=2, suppress=True)

print(img.affine)
print(img.affine.shape)

[[ -2.     0.     0.   117.86]
 [ -0.     1.97  -0.36 -35.72]
 [  0.     0.32   2.17  -7.25]
 [  0.     0.     0.     1.  ]]
(4, 4)


In [13]:
img.header

In [14]:
header = img.header
print(header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 57
dim             : [  4 128  96  24   2   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [  -1.     2.     2.     2.2 2000.     1.     1.     1. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 23
slice_code      : unknown
xyzt_units      : 10
cal_max         : 1162.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL3.3\x00 v2.25 NIfTI-1 Single file format'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : -1.9451068e-26
quatern_c       : -0.9967085
quatern_d       : -0.08106874
qoffset_x      

In [17]:
print(header.get_data_shape())
# to get the numpy data type in which the image data is stored 
# (or will be stored if you save the image)
print(header.get_data_dtype())

(128, 96, 24, 2)
int16


In [18]:
# to get the voxel sizes in millimeters
print(header.get_zooms()) 
# The last value of header.get_zooms() is the time between 
# scans in milliseconds; this is the equivalent of voxel 
# size on the time axis.

(2.0, 2.0, 2.199999, 2000.0)


In [19]:
img.dataobj

In [21]:
# You can test if the image has a array proxy like this:
nib.is_proxy(img.dataobj)

True

### Array images
We can also create images from numpy arrays. For example:

In [24]:
array_data = np.arange(24, dtype=np.int16).reshape((2, 3, 4))
affine = np.diag([1, 2, 3, 1])
array_img = nib.Nifti1Image(array_data, affine)

In [25]:
array_img.dataobj

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int16)

In [26]:
array_img.dataobj is array_data

True

In [27]:
# dataobj is an array, not an array proxy, so:
nib.is_proxy(array_img.dataobj)

False

### Getting the image data the easy way

In [31]:
image_data = array_img.get_fdata()
print(image_data.shape)
print(image_data.dtype) # == np.dtype(np.float64)

(2, 3, 4)
float64


In [32]:
image_data is array_img.dataobj

False

In [33]:
farray_img = nib.Nifti1Image(image_data.astype(np.float64), affine)
farray_data = farray_img.get_fdata()
farray_data.dtype == np.dtype(np.float64)

True

In [34]:
farray_data is farray_img.dataobj

True

In [36]:
image_data = img.get_fdata()
image_data.shape

(128, 96, 24, 2)

In [37]:
data_again = img.get_fdata()

In [38]:
data_again is image_data

True

### Image slicing

In [39]:
cropped_img = img.slicer[32:-32, ...]
cropped_img.shape

(64, 96, 24, 2)

In [41]:
np.array_equal(cropped_img.get_fdata(), 
               img.get_fdata()[32:-32, ...])

True

In [42]:
cropped_img.affine

array([[ -2.  ,   0.  ,   0.  ,  53.86],
       [ -0.  ,   1.97,  -0.36, -35.72],
       [  0.  ,   0.32,   2.17,  -7.25],
       [  0.  ,   0.  ,   0.  ,   1.  ]])

In [43]:
img.affine - cropped_img.affine

array([[ 0.,  0.,  0., 64.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [44]:
vol0 = img.slicer[..., 0]
vol0.shape

(128, 96, 24)