## [Link](https://nilearn.github.io/connectivity/functional_connectomes.html#parcellation-time-series)

In [1]:
from nilearn import plotting
import numpy as np 
import nilearn

In [2]:
data = nilearn.datasets.fetch_atlas_aal()

In [3]:
print(type(data))

<class 'sklearn.utils.Bunch'>


In [4]:
print(len(data))
print(data.keys())
print(len(data.labels))
print(len(data.indices))
# print(data.maps)
# print(data.description)

4
dict_keys(['description', 'maps', 'labels', 'indices'])
116
116


In [5]:
destrieux = nilearn.datasets.fetch_atlas_destrieux_2009()

/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py:2372: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)


In [6]:
print(len(destrieux))
print(destrieux.keys())
print(len(destrieux.labels))
# print(len(data.indices))
# print(destrieux.maps)
# print(destrieux.description)

3
dict_keys(['maps', 'labels', 'description'])
151


In [7]:
coordinates = plotting.find_parcellation_cut_coords(destrieux['maps'])

In [8]:
print(coordinates.shape)
# print(coordinates[:5, :])
# np.savetxt("data/destrieux_2009_coordinates.txt", coordinates, fmt="%18.9f")
# np.savetxt("data/destrieux_2009_labels.txt", destrieux.labels)
print(type(destrieux.labels))
print(destrieux.labels[:3])
print(type(destrieux.labels[1][1]))


(148, 3)
<class 'numpy.recarray'>
[(0, b'Background') (1, b'L G_and_S_frontomargin')
 (2, b'L G_and_S_occipital_inf')]
<class 'numpy.bytes_'>


### A functional connectome: extracting coordinates of regions
A functional connectome: extracting coordinates of regions

In [9]:
# coordinates = plotting.find_parcellation_cut_coords(
#     labels_img=yeo['thick_17'])

In [10]:
from nilearn import datasets
from nilearn import plotting

yeo = datasets.fetch_atlas_yeo_2011()
print('Yeo atlas nifti image (3D) with 17 parcels and liberal mask is located '
      'at: %s' % yeo['thick_17'])

Yeo atlas nifti image (3D) with 17 parcels and liberal mask is located at: /home/abolfazl/nilearn_data/yeo_2011/Yeo_JNeurophysiol11_MNI152/Yeo2011_17Networks_MNI152_FreeSurferConformed1mm_LiberalMask.nii.gz


In [11]:
print(yeo.keys())

dict_keys(['description', 'thin_7', 'thick_7', 'thin_17', 'thick_17', 'colors_7', 'colors_17', 'anat'])


In [12]:
coordinates = plotting.find_parcellation_cut_coords(labels_img=yeo['thick_17'])

In [13]:
print(coordinates.shape)
print(coordinates[:5, :])

(17, 3)
[[-26.08691104 -85.02461552  -1.78400214]
 [-11.44628099 -72.29265921  11.63924311]
 [-23.1343885  -25.87231899  62.18399215]
 [-51.01955636 -15.31800211  17.39336049]
 [-33.88532586 -65.32925142  21.65206863]]
